name: Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Execute npm install and deploy
        run: |
          ssh -o StrictHostKeyChecking=no articus@articus.myjino.ru << 'EOF'
            cd domains/maximpetrov.ru
            npm install
          EOF
